# Generated by Django 6.0 on 2025-12-14 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('seller', 'Seller (Lister)'), ('buyer', 'Buyer (Renter)'), ('admin', 'Administrator')], default='buyer', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Email Verification'), ('active', 'Email Verified, Pre-KYC'), ('pending_kyc', 'Waiting for KYC Review'), ('verified', 'Full Verified User'), ('rejected', 'KYC Rejected'), ('suspended', 'Account Suspended')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='userkyc',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
