# Generated by Django 5.2.6 on 2025-12-14 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_role_alter_user_status_alter_userkyc_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userkyc',
            options={'get_latest_by': 'submitted_at', 'ordering': ['-submitted_at']},
        ),
        migrations.AddField(
            model_name='userkyc',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2025, 1, 1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userkyc',
            name='kyc_type',
            field=models.CharField(choices=[('aadhaar', 'Aadhaar'), ('pan', 'PAN')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userkyc',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='submitted', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='userkyc',
            unique_together={('kyc_type', 'kyc_identifier')},
        ),
    ]
