# Generated by Django 5.2.6 on 2025-12-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userkyc_options_userkyc_submitted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Email Verification'), ('active', 'Email Verified, Pre-KYC'), ('verified', 'Full Verified User'), ('rejected', 'KYC Rejected'), ('suspended', 'Account Suspended')], default='pending', max_length=20),
        ),
    ]
