# Generated by Django 5.2.6 on 2025-12-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkyc',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='kyc_documents/', verbose_name='KYC Document Upload'),
        ),
        migrations.AlterField(
            model_name='userkyc',
            name='kyc_identifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
