# Generated by Django 5.2.6 on 2025-12-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userkyc_document_file_alter_userkyc_kyc_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkyc',
            name='review_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
