# Generated by Django 5.2.6 on 2025-12-16 07:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userkyc_review_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Time of the last password update for JWT validation.'),
        ),
    ]
