# Generated by Django 5.2.6 on 2025-12-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetotp',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='passwordresetotp',
            table='users_password_reset_otp',
        ),
    ]
