# Generated by Django 5.2.6 on 2025-12-19 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_passwordresetotp_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetOTP',
        ),
    ]
