# Generated by Django 5.2.6 on 2025-12-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimage',
            name='image',
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='image_url',
            field=models.URLField(default='https://placeholder.com/default-image.jpg', help_text='The external Cloudinary URL for the image.', max_length=500),
            preserve_default=False,
        ),
    ]
